[tool.ruff]
line-length = 120
select = ["ALL"]
ignore = [
    "ANN401", #Disallow Any
    "D401", #Imperative mood
    "RUF012", #ignore till https://github.com/astral-sh/ruff/issues/5243
    "UP004" #useless-object-inheritance
]
target-version = "py38"
fix = true
show-fixes = true
[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"**test.py" = ["S101","SLF001","PT019","S311"]


[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 120

[tool.black]
line-length = 120

[pycodestyle]
max-line-length = 120
exclude = ["venv"]


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

[tools.pytest]
pythonpath = ["esxport"]

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report=xml --cov-report term-missing --ff -x --no-cov-on-fail --emoji --dist loadgroup --tx=4*popen"

[tool.coverage.run]
#branch = true #https://github.com/nedbat/coveragepy/issues/605
parallel = true

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing=true
sort="-Stmts"
omit = ["test/**"]
exclude_lines = [
    'if TYPE_CHECKING:',
    'if __name__ == "__main__":'
    ]



[tool.pyright]
include = ["."]
typeCheckingMode = "strict"
exclude = ["**/test",]
reportMissingTypeStubs = false
